add get_next_line() func
write custom function to parse file line by line instead of using
getline.

compil error when i try to compil with getline : /home/segfault42/Documents/nXDownload/source/download.c:276: undefined reference to `getline'

see here for more info : https://stackoverflow.com/questions/13112784/undefined-reference-to-getline-in-c